macos_instance:
  image: macos-monterey-base:latest
  cpu: 12
  memory: 24G

task:
  script: 
   - echo "Hello World from macOS!"
   - brew install --cask docker
   - open --hide --background -a Docker
   - docker info
