macos_instance:
  image: ghcr.io/cirruslabs/macos-monterey-base:latest

task:
  script: 
   - echo "Hello World from macOS!"
   - brew cask install docker
   - open --hide --background -a docker
   - docker info
